# -*- coding: utf-8 -*-
"""Reseach paper summarisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGPsAVhbIC7v-dx4NfMpLtv0FBX20Q9M

# **ArXiv Project**
"""

pip install arxiv

import arxiv
import pandas as pd
from transformers import pipeline

query='AI or artificial intelligence or machine learning'
search=arxiv.Search(query=query,max_results=10,sort_by=arxiv.SortCriterion.SubmittedDate)
papers=[]
for result in search.results():
  papers.append(
      {
          'published':result.published,
          'title':result.title,
          'abstract':result.summary,
          'categories':result.categories
      }
  )
df=pd.DataFrame(papers)
df.head()

summarize=pipeline("summarization",model="facebook/bart-large-cnn")

abstract=df['abstract'][0]
summarisation_result=summarize(abstract)
summarisation_result[0]['summary_text']